import 'package:flutter/widgets.dart';
import 'package:my_life/features/expense/domain/expense_record.dart';

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  bool get _isKorean => locale.languageCode == 'ko';

  String get(String key, {Map<String, Object> values = const {}}) {
    var text = (_isKorean ? _ko : _en)[key] ?? key;
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return text;
  }

  String expenseCategory(ExpenseCategory category) => get(switch (category) {
    ExpenseCategory.food => 'categoryFood',
    ExpenseCategory.transport => 'categoryTransport',
    ExpenseCategory.shopping => 'categoryShopping',
    ExpenseCategory.entertainment => 'categoryEntertainment',
    ExpenseCategory.travel => 'categoryTravel',
    ExpenseCategory.housing => 'categoryHousing',
    ExpenseCategory.subscription => 'categorySubscription',
    ExpenseCategory.other => 'other',
  });

  String paymentMethod(PaymentMethod method) => get(switch (method) {
    PaymentMethod.cash => 'paymentCash',
    PaymentMethod.card => 'paymentCard',
    PaymentMethod.transfer => 'paymentTransfer',
    PaymentMethod.other => 'other',
  });

  static const _ko = <String, String>{
    'home': '홈',
    'timeline': '타임라인',
    'finance': '재정',
    'me': '나',
    'recordAdd': '기록 추가',
    'appError': '화면을 열 수 없습니다.',
    'homeMessage': '나의 기록을 한곳에서 천천히 쌓아갑니다.',
    'homeMonthlyExpense': '이번 달 지출',
    'paymentImport': '지출 가져오기',
    'paymentImportHint': '결제 알림을 확인하고 지출로 저장합니다.',
    'paymentImportDescription': '연결을 켜면 결제 알림에서 지출 초안을 만듭니다. 확인 후 저장하며 원본 알림은 변경하지 않습니다. 데이터는 기기에만 저장됩니다.',
    'paymentImportEnable': '결제 알림 가져오기 허용',
    'paymentAccessExplanation': 'Android 알림 접근 권한은 전체 알림에 접근할 수 있는 권한입니다. MY LIFE는 아래에서 선택한 앱의 결제 알림만 처리합니다.',
    'paymentAccessSettings': '알림 접근 설정 열기',
    'paymentAccessMissing': '시스템 설정에서 MY LIFE의 알림 접근을 허용해주세요.',
    'paymentSelectApps': '결제 알림을 받을 카드·은행 앱 선택',
    'paymentShortcutInstructions': 'iPhone에서는 단축어 자동화를 직접 설정합니다. iOS 27의 앱 알림 또는 메시지 수신을 조건으로 선택하고, 전달된 결제 텍스트를 URL 인코딩해 아래 URL 뒤에 붙인 뒤 URL 열기를 실행하세요. 알림 텍스트 전달 여부는 기기에서 확인해야 합니다. 앱을 열어 미확인 지출에서 확인 후 저장합니다.',
    'paymentCopyUrl': '단축어 연결 URL 복사',
    'paymentPending': '미확인 지출',
    'paymentRefresh': '가져온 알림 확인',
    'paymentEmpty': '확인할 결제 알림이 없습니다.',
    'paymentDismiss': '가져온 항목 버리기',
    'paymentReviewHint':
        '원본 알림을 확인하고 금액·카테고리·사용처·날짜를 수정한 뒤 저장하세요. 날짜가 없으면 알림 수신 시각을 제안합니다.',
    'paymentImportError': '지출 알림을 가져오지 못했습니다. 다시 시도해주세요.',
    'calendarAutoSync': '캘린더 변경 자동 반영',
    'calendarAutoSyncHint': '선택한 캘린더와 기간의 변경을 앱 실행·복귀 시와 사용 중 5분마다 확인합니다. 원본은 변경하지 않고, 직접 수정한 메모는 보호합니다.',
    'calendarSyncApply': '현재 선택한 캘린더와 기간으로 갱신',
    'calendarSyncDisable': '자동 반영 끄기',
    'calendarSyncRange': '저장된 동기화 기간: {start} – {end}',
    'calendarSyncResult':
        '추가 {imported} · 수정 {updated} · 삭제 {removed} · 직접 수정 보호 {protected}',
    'homeRecentRecords': '최근 기록',
    'homeRecentPhotos': '최근 사진',
    'homeExpenseEmpty': '이번 달에는 아직 지출 기록이 없어요.',
    'homePhotosEmpty': '아직 사진 기록이 없어요.',
    'homeLoadError': '정보를 불러오지 못했습니다. 다시 시도해주세요.',
    'homePhotoUnavailable': '사진을 표시할 수 없습니다.',
    'timelineMessage': '기록이 생기면 날짜순으로 이곳에 표시됩니다.',
    'filterAll': '전체',
    'dateRange': '기간',
    'clearDateRange': '기간 선택 지우기',
    'timelineEmptyTitle': '아직 기록이 없어요',
    'timelineEmptyBody': '+ 버튼으로 첫 기록을 남겨보세요.',
    'timelineLoadError': '타임라인을 불러오지 못했습니다.',
    'retry': '다시 시도',
    'financeTotal': '총 지출',
    'financeCategories': '카테고리별 지출',
    'financeDays': '일별 지출',
    'financeEmpty': '선택한 달에는 아직 지출 기록이 없어요.',
    'financeLoadError': '지출 요약을 불러오지 못했습니다. 다시 시도해주세요.',
    'previousMonth': '이전 달',
    'nextMonth': '다음 달',
    'currentMonth': '이번 달',
    'record': '기록하기',
    'recordQuestion': '무엇을 기록할까요?',
    'memo': '메모',
    'expense': '지출',
    'photo': '사진',
    'photosCount': '사진 {count}장',
    'edit': '수정',
    'delete': '삭제',
    'cancel': '취소',
    'save': '저장',
    'titleOptional': '제목 (선택)',
    'contentOptional': '내용 (선택)',
    'memoOptional': '메모 (선택)',
    'placeOptional': '장소 (선택)',
    'date': '날짜',
    'time': '시간',
    'notSelected': '선택 안 함',
    'clearSelection': '선택 지우기',
    'loadError': '기록을 불러오지 못했습니다.\n다시 시도해주세요.',
    'notFound': '기록을 찾을 수 없습니다.',
    'goHome': 'Home으로 가기',
    'memoEdit': '메모 수정',
    'memoRequired': '제목 또는 내용을 입력해주세요.',
    'memoSaveError': '메모를 저장하지 못했습니다. 다시 시도해주세요.',
    'memoDeleteTitle': '메모를 삭제할까요?',
    'memoDeleteBody': '삭제한 메모는 앱에서 보이지 않습니다.',
    'memoDeleteError': '메모를 삭제하지 못했습니다. 다시 시도해주세요.',
    'expenseEdit': '지출 수정',
    'amount': '금액',
    'won': '원',
    'amountRequired': '0원보다 큰 금액을 입력해주세요.',
    'category': '카테고리',
    'paymentMethod': '결제 방법',
    'categoryFood': '식비',
    'categoryTransport': '교통',
    'categoryShopping': '쇼핑',
    'categoryEntertainment': '문화·여가',
    'categoryTravel': '여행',
    'categoryHousing': '주거',
    'categorySubscription': '구독',
    'other': '기타',
    'paymentCash': '현금',
    'paymentCard': '카드',
    'paymentTransfer': '계좌이체',
    'expenseSaveError': '지출을 저장하지 못했습니다. 다시 시도해주세요.',
    'expenseDeleteTitle': '지출 기록을 삭제할까요?',
    'expenseDeleteBody': '삭제한 지출은 앱에서 보이지 않습니다.',
    'expenseDeleteError': '지출을 삭제하지 못했습니다. 다시 시도해주세요.',
    'photoEdit': '사진 수정',
    'gallery': '갤러리',
    'camera': '카메라',
    'photoRequired': '사진을 한 장 이상 선택해주세요.',
    'photoNumber': '사진 {count}',
    'reorderHint': '길게 눌러 순서를 바꿀 수 있어요.',
    'removeSelection': '선택 제거',
    'photoEditHint': '사진은 상세 화면에서 개별로 삭제할 수 있습니다.',
    'photoPickError': '사진을 가져오지 못했습니다. 다시 시도해주세요.',
    'photoSaveError': '사진 기록을 저장하지 못했습니다.',
    'photoDelete': '사진 삭제',
    'photoDeleteTitle': '이 사진을 삭제할까요?',
    'photoDeleteBody': '앱에 복사된 사진만 삭제되며 갤러리 원본은 유지됩니다.',
    'photoRecordDeleteTitle': '전체 기록을 삭제할까요?',
    'lastPhotoDeleteTitle': '사진 기록을 삭제할까요?',
    'lastPhotoDeleteBody': '마지막 사진을 삭제하면 이 사진 기록도 함께 삭제됩니다.',
    'photoRecordDeleteBody': '앱에 복사된 사진과 이 기록이 모두 삭제됩니다.',
    'photoDeleteError': '사진을 삭제하지 못했습니다. 다시 시도해주세요.',
    'language': '언어',
    'korean': '한국어',
    'english': '영어',
    'languageHint': '앱에 표시할 언어를 선택하세요.',
    'languageSaveError': '언어 설정을 저장하지 못했습니다. 이전 언어로 돌아갑니다. 다시 시도해주세요.',
    'appInformation': '앱 정보',
    'appVersion': '앱 버전',
    'openSourceLicenses': '오픈소스 라이선스',
    'appInfoError': '앱 정보를 불러오지 못했습니다.',
    'localStorageTitle': '내 기기의 기록',
    'localStorageWarning': '기록과 앱에 복사한 사진은 이 기기에 저장됩니다. 현재 백업·복원과 기기 간 동기화는 지원하지 않습니다. 앱 삭제, 앱 데이터 초기화 또는 기기 분실 시 기록을 잃을 수 있습니다. 갤러리 원본은 앱에서 삭제하지 않습니다.',
    'connections': '연결',
    'calendarImport': '캘린더 가져오기',
    'calendarImportHint': '선택한 일정을 메모로 가져옵니다.',
    'calendarImportDescription':
        '선택한 기간의 일정을 메모로 한 번 가져옵니다. 원본 캘린더는 변경하지 않습니다.',
    'calendarPermissionTitle': '캘린더 접근이 필요해요',
    'calendarPermissionBody': '사용자가 선택한 일정을 읽으려면 캘린더 접근을 허용해주세요.',
    'calendarPermissionRestricted': '기기 정책으로 캘린더 접근이 제한되어 있습니다.',
    'allowCalendarAccess': '캘린더 접근 허용',
    'openSettings': '설정 열기',
    'importPeriod': '가져올 기간',
    'selectCalendars': '캘린더 선택',
    'primaryCalendar': '기본 캘린더',
    'noCalendars': '가져올 수 있는 캘린더가 없습니다.',
    'importSelectedEvents': '선택한 일정 가져오기',
    'calendarImportResult': '{imported}개를 가져오고 {skipped}개를 건너뛰었습니다.',
    'calendarImportError': '캘린더를 불러오지 못했습니다.',
    'calendarSettingsSaveError': '캘린더 설정을 저장하지 못했습니다. 이전 설정을 유지합니다. 다시 시도해주세요.',
    'photoMetadataApplied': '사진의 촬영 날짜와 장소를 입력했습니다. 저장 전에 확인해주세요.',
  };

  static const _en = <String, String>{
    'home': 'Home',
    'timeline': 'Timeline',
    'finance': 'Finance',
    'me': 'Me',
    'recordAdd': 'Add record',
    'appError': 'This screen could not be opened.',
    'homeMessage': 'A calm place for your personal records.',
    'homeMonthlyExpense': 'This month’s expenses',
    'paymentImport': 'Import expenses',
    'paymentImportHint': 'Review payment alerts and save expenses.',
    'paymentImportDescription': 'Enable this connection to prepare drafts from payment alerts. Review before saving. Original notifications are unchanged; data stays on this device.',
    'paymentImportEnable': 'Allow payment alert import',
    'paymentAccessExplanation': 'Android notification access can read all notifications. MY LIFE only processes payment alerts from the apps you select below.',
    'paymentAccessSettings': 'Open notification access settings',
    'paymentAccessMissing':
        'Allow notification access for MY LIFE in system settings.',
    'paymentSelectApps': 'Select your card and bank apps',
    'paymentShortcutInstructions': 'Set up a Shortcuts automation on your iPhone. Choose an app notification on iOS 27 or an incoming message as the trigger. URL-encode the payment text, append it to the URL below, then use Open URL. Verify that your device passes the notification text. Open MY LIFE and review pending expenses before saving.',
    'paymentCopyUrl': 'Copy Shortcuts URL',
    'paymentPending': 'Pending expenses',
    'paymentRefresh': 'Check imported alerts',
    'paymentEmpty': 'No payment alerts to review.',
    'paymentDismiss': 'Discard imported item',
    'paymentReviewHint': 'Check the original alert, amount, category, merchant and date before saving. When no date is present, the receipt time is suggested.',
    'paymentImportError': 'Could not import payment alerts. Please try again.',
    'calendarAutoSync': 'Automatically reflect calendar changes',
    'calendarAutoSyncHint': 'Checks the selected calendars and dates on launch, resume and every 5 minutes while in use. Originals are unchanged; locally edited memos are protected.',
    'calendarSyncApply': 'Apply current calendars and dates',
    'calendarSyncDisable': 'Disable automatic updates',
    'calendarSyncRange': 'Saved sync range: {start} – {end}',
    'calendarSyncResult': 'Added {imported} · updated {updated} · removed {removed} · local edits protected {protected}',
    'homeRecentRecords': 'Recent records',
    'homeRecentPhotos': 'Recent photos',
    'homeExpenseEmpty': 'No expenses recorded this month yet.',
    'homePhotosEmpty': 'No photo records yet.',
    'homeLoadError': 'Could not load this section. Please try again.',
    'homePhotoUnavailable': 'Photo unavailable.',
    'timelineMessage': 'Your records will appear here in date order.',
    'filterAll': 'All',
    'dateRange': 'Date range',
    'clearDateRange': 'Clear date range',
    'timelineEmptyTitle': 'No records yet',
    'timelineEmptyBody': 'Use the + button to add your first record.',
    'timelineLoadError': 'Could not load the timeline.',
    'retry': 'Try again',
    'financeTotal': 'Total expenses',
    'financeCategories': 'By category',
    'financeDays': 'Daily expenses',
    'financeEmpty': 'No expenses recorded for this month yet.',
    'financeLoadError': 'Could not load expenses. Please try again.',
    'previousMonth': 'Previous month',
    'nextMonth': 'Next month',
    'currentMonth': 'This month',
    'record': 'New record',
    'recordQuestion': 'What would you like to record?',
    'memo': 'Memo',
    'expense': 'Expense',
    'photo': 'Photo',
    'photosCount': '{count} photos',
    'edit': 'Edit',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'save': 'Save',
    'titleOptional': 'Title (optional)',
    'contentOptional': 'Content (optional)',
    'memoOptional': 'Memo (optional)',
    'placeOptional': 'Place (optional)',
    'date': 'Date',
    'time': 'Time',
    'notSelected': 'Not selected',
    'clearSelection': 'Clear selection',
    'loadError': 'Could not load the record.\nPlease try again.',
    'notFound': 'The record could not be found.',
    'goHome': 'Go to Home',
    'memoEdit': 'Edit memo',
    'memoRequired': 'Enter a title or content.',
    'memoSaveError': 'Could not save the memo. Please try again.',
    'memoDeleteTitle': 'Delete this memo?',
    'memoDeleteBody': 'The deleted memo will no longer appear in the app.',
    'memoDeleteError': 'Could not delete the memo. Please try again.',
    'expenseEdit': 'Edit expense',
    'amount': 'Amount',
    'won': 'KRW',
    'amountRequired': 'Enter an amount greater than zero.',
    'category': 'Category',
    'paymentMethod': 'Payment method',
    'categoryFood': 'Food',
    'categoryTransport': 'Transport',
    'categoryShopping': 'Shopping',
    'categoryEntertainment': 'Entertainment',
    'categoryTravel': 'Travel',
    'categoryHousing': 'Housing',
    'categorySubscription': 'Subscription',
    'other': 'Other',
    'paymentCash': 'Cash',
    'paymentCard': 'Card',
    'paymentTransfer': 'Transfer',
    'expenseSaveError': 'Could not save the expense. Please try again.',
    'expenseDeleteTitle': 'Delete this expense?',
    'expenseDeleteBody':
        'The deleted expense will no longer appear in the app.',
    'expenseDeleteError': 'Could not delete the expense. Please try again.',
    'photoEdit': 'Edit photo record',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'photoRequired': 'Select at least one photo.',
    'photoNumber': 'Photo {count}',
    'reorderHint': 'Press and hold to change the order.',
    'removeSelection': 'Remove selection',
    'photoEditHint': 'Individual photos can be removed from the detail screen.',
    'photoPickError': 'Could not import the photo. Please try again.',
    'photoSaveError': 'Could not save the photo record.',
    'photoDelete': 'Delete photo',
    'photoDeleteTitle': 'Delete this photo?',
    'photoDeleteBody':
        'Only the app copy will be deleted. Your gallery original remains.',
    'photoRecordDeleteTitle': 'Delete the entire record?',
    'lastPhotoDeleteTitle': 'Delete this photo record?',
    'lastPhotoDeleteBody':
        'Deleting the last photo also deletes this photo record.',
    'photoRecordDeleteBody':
        'The record and all app-managed photo copies will be deleted.',
    'photoDeleteError': 'Could not delete the photo. Please try again.',
    'language': 'Language',
    'korean': 'Korean',
    'english': 'English',
    'languageHint': 'Choose the language used in the app.',
    'languageSaveError': 'Could not save the language. Your previous language has been restored. Please try again.',
    'appInformation': 'App information',
    'appVersion': 'App version',
    'openSourceLicenses': 'Open source licenses',
    'appInfoError': 'Could not load app information.',
    'localStorageTitle': 'Records on this device',
    'localStorageWarning': 'Records and app-managed photo copies are stored on this device. Backup, restore and multi-device sync are not available. Uninstalling, clearing app data or losing this device can lose your records. Gallery originals are never deleted by the app.',
    'connections': 'Connections',
    'calendarImport': 'Import calendar',
    'calendarImportHint': 'Import selected events as memos.',
    'calendarImportDescription': 'Import events in the selected range once as memos. Your original calendar is never changed.',
    'calendarPermissionTitle': 'Calendar access required',
    'calendarPermissionBody':
        'Allow calendar access so you can choose events to import.',
    'calendarPermissionRestricted':
        'Calendar access is restricted by a device policy.',
    'allowCalendarAccess': 'Allow calendar access',
    'openSettings': 'Open settings',
    'importPeriod': 'Import period',
    'selectCalendars': 'Select calendars',
    'primaryCalendar': 'Primary calendar',
    'noCalendars': 'No calendars are available to import.',
    'importSelectedEvents': 'Import selected events',
    'calendarImportResult': 'Imported {imported}; skipped {skipped}.',
    'calendarImportError': 'Could not load the calendar.',
    'calendarSettingsSaveError': 'Could not save calendar settings. Previous settings remain in effect. Please try again.',
    'photoMetadataApplied': 'The photo date and place were filled in. Please review them before saving.',
  };
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings(Localizations.localeOf(this));
}
